apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - service.yaml
  - statefulset.yaml
  - secret.yaml
  - configmap.yaml
  - service-account.yaml
  - network-policy.yaml
  - orbiter-service.yaml
  - orbiter-statefulset.yaml
