apiVersion: v1
kind: Service
metadata:
  name: queue-master
  # annotations:
  #   prometheus.io/scrape: 'true'
  labels:
    name: queue-master
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: queue-master
