apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: catalogue-access
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: catalogue
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              name: front-end
      ports:
        - protocol: TCP
          port: 8080 # (the target port your pod is listening on/containerPort)
