apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cart-db-access
  namespace: database
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cart-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: # and don't forget to: kubectl label namespace sockshop name=sockshop and to verify: kubectl get namespace sockshop --show-labels
            matchLabels:
              name: sockshop
          podSelector:
            matchLabels:
              name: carts
      ports:
        - protocol: TCP
          port: 27017
