apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: orders-access
spec:
  podSelector:
    matchLabels:
      name: orders
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              name: front-end
        - namespaceSelector:
            matchLabels:
              name: database
          podSelector:
            matchLabels:
              app.kubernetes.io/name: order-db
      ports:
        - protocol: TCP
          port: 80
