apiVersion: v1
kind: Service
metadata:
  name: user-db
  labels:
    app: user-db
  namespace: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    app: user-db
