apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db
  labels:
    app: user-db
spec:
  serviceName: user-db
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: mongo
          image: mongo:3
          command: ["mongod", "--config", "/etc/mongodb.conf", "--smallfiles"]
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: db-data
              mountPath: /data/db-users
            - name: mongo-conf
              mountPath: /etc/mongodb.conf
              subPath: mongodb.conf
            - name: mongo-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongo-conf
          configMap:
            name: user-db-config
        - name: mongo-init
          configMap:
            name: mongo-init-scripts
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
