apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: carts
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: carts
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
# ------------------------------------------------------------------
# Enhancements:
# instead of using autoscaling/v2 instead of autoscaling/v1
# so metrics ... instead of   targetCPUUtilizationPercentage: 50
# ------------------------------------------------------------------
