apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cart-access
spec:
  podSelector:
    matchLabels:
      name: carts
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              name: front-end
        - podSelector:
            matchLabels:
              name: orders
        - namespaceSelector:
            matchLabels:
              name: database
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cart-db
      ports:
        - protocol: TCP
          port: 80 # (the target port your pod is listening on/containerPort)
